ARG BASE_IMAGE=leya/erpnext:v16.32.0-xasdsdsa-81a6f975
FROM ${BASE_IMAGE}

USER root

RUN rm -rf /home/frappe/frappe-bench/apps/frappe /home/frappe/frappe-bench/apps/erpnext

COPY --chown=frappe:frappe frappe-source /home/frappe/frappe-bench/apps/frappe
COPY --chown=frappe:frappe erpnext-source /home/frappe/frappe-bench/apps/erpnext

RUN rm -rf \
		/home/frappe/frappe-bench/apps/frappe/.git \
		/home/frappe/frappe-bench/apps/erpnext/.git \
		/home/frappe/frappe-bench/sites/assets \
	&& ln -s \
		/home/frappe/frappe-bench/assets \
		/home/frappe/frappe-bench/sites/assets \
	&& chown -h frappe:frappe /home/frappe/frappe-bench/sites/assets

USER frappe
WORKDIR /home/frappe/frappe-bench

RUN yarn --cwd apps/frappe install --frozen-lockfile \
	&& yarn --cwd apps/erpnext install --frozen-lockfile \
	&& yarn --cwd apps/erpnext/banking install --frozen-lockfile \
	&& yarn --cwd apps/erpnext/banking build \
	&& bench build --production \
	&& bench compile-po-to-mo --app frappe --locale zh --force \
	&& bench compile-po-to-mo --app erpnext --locale zh --force \
	&& env/bin/python apps/erpnext/deploy/verify_zh_cn_image.py \
	&& rm -rf node_modules/.cache
